### ISSUE TITLE
Publish a Poll

### ISSUE THREAD

**Issue by diegomoro4** [Diegomoro415/CI-love-running#5]
In order to **automatically hide the poll ** as a **administrator**, I can **pick the expiry date while publishing the poll**

**Comment by diegomoro4** [comment]
## Acceptance Criteria:

* The poll should disappear at 11:59 PM on the target date.
* The real estate of the "Poll" should be reserved on the home page. a message that says " Stay Tuned, a new poll is coming soon" should appear if no other Poll is active.
* The administrator expiry date should be at least 3 days after the current date.

## Tasks
- [ ] Update the admin module view: the poll design (HTML and CSS) to include date picker.
- [ ] Update the website view: show "Stay tuned, a new poll is coming soon".
- [ ] Create Javascript function to validate the expiry date is at least after 3 days.
- [ ] Create a job check expired Polls everyday at 11:59 PM and Hide them.
- [ ] Update the controller function
- [ ] Update unit test scripts.
- [ ] Test the functionality.

**Comment by Diegomoro415** [comment]
add acceptance criteria to publish a poll user story
